name: frenchinjapan
favicon: null
layout_spectrum: 0.9597333318088204
typography_spectrum: 0.45890646730549634
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6161385346204042
  lightness: 0.7562985222321004
  saturation: 0.7972141481004655
  rhythmicContrast: 0.6418699342757463
purpose: []
