name: frenchinjapan
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1469534
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: FrenchInJapan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#36373b'
    - '#fc414a'
    - '#c6997c'
    - '#ff0000'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
